# Gum Styling

# Choose
export $GUM_CHOOSE_CURSOR_FOREGROUND="#123"
export $GUM_CHOOSE_CURSOR_BACKGROUND="#999"
export $GUM_CHOOSE_HEADER_FOREGROUND="#123"
export $GUM_CHOOSE_HEADER_BACKGROUND="#3FF"
export $GUM_CHOOSE_ITEM_FOREGROUND="#123"
export $GUM_CHOOSE_ITEM_BACKGROUND="#3FF"
export $GUM_CHOOSE_SELECTED_FOREGROUND="#F13"
export $GUM_CHOOSE_SELECTED_BACKGROUND="#3FF"

# Input
export GUM_INPUT_CURSOR_FOREGROUND="#FF0"
export GUM_INPUT_PROMPT_FOREGROUND="#0FF"
export GUM_INPUT_PLACEHOLDER="What's up?"
export GUM_INPUT_PROMPT="* "
export GUM_INPUT_WIDTH=80